[package]
name = "bench-cargo-profiles"
version = "0.1.0"
authors = ["Brian Anderson <andersrb@gmail.com>"]
edition = "2018"

[dependencies]
failure = "0.1.5"
serde = "1.0.89"
serde_derive = "1.0.89"
serde_json = "1.0.39"
clap = "2.32.0"
structopt = "0.2.15"
